apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ugc-marketplace.fullname" . }}-secrets
  labels:
    {{- include "ugc-marketplace.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
