apiVersion: v1
kind: Service
metadata:
  name: {{ include "ugc-marketplace.fullname" . }}
  labels:
    {{- include "ugc-marketplace.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: {{ .Values.service.protocol }}
      name: http
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.config.METRICS_PORT }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "ugc-marketplace.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
