"""Analytics API endpoints for the UGC Marketplace."""

from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from pydantic import BaseModel, Field

from ugc_marketplace.security.auth import get_current_user, require_auth
from ugc_marketplace.security.authorization import Permission, require_permission

router = APIRouter(prefix="/api/v1/analytics", tags=["analytics"])


# ---------------------------------------------------------------------------
# Pydantic Models
# ---------------------------------------------------------------------------


class DashboardMetrics(BaseModel):
    """Top-level marketplace dashboard metrics."""

    total_creators: int = Field(..., description="Total number of creators")
    total_content_items: int = Field(..., description="Total content items published")
    total_revenue: float = Field(..., description="Total marketplace revenue")
    total_transactions: int = Field(..., description="Total number of transactions")
    active_creators_30d: int = Field(..., description="Creators active in the last 30 days")
    content_published_30d: int = Field(..., description="Content published in the last 30 days")
    revenue_30d: float = Field(..., description="Revenue generated in the last 30 days")
    avg_transaction_value: float = Field(..., description="Average transaction value")
    period_start: datetime = Field(..., description="Analytics period start")
    period_end: datetime = Field(..., description="Analytics period end")


class CreatorAnalytics(BaseModel):
    """Per-creator analytics record."""

    creator_id: str = Field(..., description="Creator unique identifier")
    creator_name: str = Field(..., description="Creator display name")
    content_count: int = Field(..., description="Number of content items")
    total_views: int = Field(..., description="Total content views")
    total_likes: int = Field(..., description="Total content likes")
    total_shares: int = Field(..., description="Total content shares")
    total_revenue: float = Field(..., description="Revenue attributed to creator")
    avg_engagement_rate: float = Field(..., description="Average engagement rate (0-1)")
    follower_count: int = Field(..., description="Current follower count")
    rank: int = Field(..., description="Creator rank by revenue")


class ContentAnalytics(BaseModel):
    """Per-content-item analytics record."""

    content_id: str = Field(..., description="Content unique identifier")
    creator_id: str = Field(..., description="Owning creator identifier")
    title: str = Field(..., description="Content title")
    content_type: str = Field(..., description="Type of content (video, image, text)")
    views: int = Field(..., description="Total views")
    likes: int = Field(..., description="Total likes")
    shares: int = Field(..., description="Total shares")
    comments: int = Field(..., description="Total comments")
    revenue: float = Field(..., description="Revenue generated by this content")
    engagement_rate: float = Field(..., description="Engagement rate (0-1)")
    published_at: datetime = Field(..., description="Publication timestamp")


class RevenueAnalytics(BaseModel):
    """Revenue analytics summary."""

    total_revenue: float = Field(..., description="Total revenue in period")
    total_transactions: int = Field(..., description="Total transactions in period")
    avg_transaction_value: float = Field(..., description="Average transaction value")
    top_earning_creators: list[dict[str, Any]] = Field(
        default_factory=list, description="Top earning creators"
    )
    revenue_by_content_type: dict[str, float] = Field(
        default_factory=dict, description="Revenue breakdown by content type"
    )
    daily_revenue: list[dict[str, Any]] = Field(
        default_factory=list, description="Daily revenue time series"
    )
    period_start: datetime = Field(..., description="Period start")
    period_end: datetime = Field(..., description="Period end")


class AnalyticsResponse(BaseModel):
    """Generic analytics response wrapper."""

    success: bool = True
    data: Any | None = None
    message: str | None = None


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get(
    "",
    response_model=AnalyticsResponse,
    summary="Get marketplace analytics dashboard",
    description="Returns high-level marketplace analytics including totals, "
    "30-day activity, and key performance indicators.",
)
async def get_dashboard_analytics(
    request: Request,
    user=Depends(require_permission(Permission.ANALYTICS_READ)),
) -> AnalyticsResponse:
    """Retrieve the marketplace analytics dashboard."""
    try:
        now = datetime.utcnow()
        data = DashboardMetrics(
            total_creators=0,
            total_content_items=0,
            total_revenue=0.0,
            total_transactions=0,
            active_creators_30d=0,
            content_published_30d=0,
            revenue_30d=0.0,
            avg_transaction_value=0.0,
            period_start=now,
            period_end=now,
        )
        return AnalyticsResponse(data=data)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to retrieve dashboard analytics: {exc}",
        )


@router.get(
    "/creators",
    response_model=AnalyticsResponse,
    summary="Get creator analytics",
    description="Returns analytics for all creators including engagement, "
    "revenue, and ranking data.",
)
async def get_creator_analytics(
    request: Request,
    limit: int = Query(default=50, ge=1, le=200, description="Max creators to return"),
    sort_by: str = Query(
        default="revenue", description="Sort field (revenue, engagement, followers)"
    ),
    user=Depends(require_permission(Permission.ANALYTICS_READ)),
) -> AnalyticsResponse:
    """Retrieve creator analytics."""
    try:
        creators: list[CreatorAnalytics] = []
        return AnalyticsResponse(data=creators)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to retrieve creator analytics: {exc}",
        )


@router.get(
    "/content",
    response_model=AnalyticsResponse,
    summary="Get content analytics",
    description="Returns analytics for content items including views, "
    "engagement, and revenue per item.",
)
async def get_content_analytics(
    request: Request,
    limit: int = Query(default=50, ge=1, le=200, description="Max content items to return"),
    content_type: str | None = Query(default=None, description="Filter by content type"),
    user=Depends(require_permission(Permission.ANALYTICS_READ)),
) -> AnalyticsResponse:
    """Retrieve content analytics."""
    try:
        content: list[ContentAnalytics] = []
        return AnalyticsResponse(data=content)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to retrieve content analytics: {exc}",
        )


@router.get(
    "/revenue",
    response_model=AnalyticsResponse,
    summary="Get revenue analytics",
    description="Returns revenue analytics including totals, top earners, "
    "breakdowns by content type, and daily time series.",
)
async def get_revenue_analytics(
    request: Request,
    days: int = Query(default=30, ge=1, le=365, description="Number of days to include"),
    user=Depends(require_permission(Permission.ANALYTICS_READ)),
) -> AnalyticsResponse:
    """Retrieve revenue analytics."""
    try:
        now = datetime.utcnow()
        data = RevenueAnalytics(
            total_revenue=0.0,
            total_transactions=0,
            avg_transaction_value=0.0,
            top_earning_creators=[],
            revenue_by_content_type={},
            daily_revenue=[],
            period_start=now,
            period_end=now,
        )
        return AnalyticsResponse(data=data)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to retrieve revenue analytics: {exc}",
        )
