apiVersion: v1
kind: Service
metadata:
  name: ugc-marketplace
  namespace: ugc-marketplace
  labels:
    app: ugc-marketplace
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: ugc-marketplace
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
