apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patches:
  - path: deployment-patch.yaml

configMapGenerator:
  - name: ugc-marketplace-config
    behavior: merge
    literals:
      - APP_ENV=development
      - LOG_LEVEL=DEBUG
