apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

labels:
  - includeSelectors: true
    pairs:
      app: ugc-marketplace
      managed-by: kustomize

images:
  - name: ugc-marketplace
    newTag: latest
